#include <vector>
#include "SDL.h"

std::vector <SDL_Rect*> InitEnemyList()
{
  std::vector <SDL_Rect*> List;
  SDL_Rect *Enemy1 = new SDL_Rect;
  SDL_Rect *Enemy2 = new SDL_Rect;
  SDL_Rect *Enemy3 = new SDL_Rect;
  SDL_Rect *Enemy4 = new SDL_Rect;
  SDL_Rect *Enemy5 = new SDL_Rect;
  SDL_Rect *Enemy6 = new SDL_Rect;
  SDL_Rect *Enemy7 = new SDL_Rect;
  SDL_Rect *Enemy8 = new SDL_Rect;
  SDL_Rect *Enemy9 = new SDL_Rect;
  SDL_Rect *Enemy10 = new SDL_Rect;
  SDL_Rect *Enemy11 = new SDL_Rect;
  SDL_Rect *Enemy12 = new SDL_Rect;
  SDL_Rect *Enemy13 = new SDL_Rect;
  SDL_Rect *Enemy14 = new SDL_Rect;
  SDL_Rect *Enemy15 = new SDL_Rect;
  SDL_Rect *Enemy16 = new SDL_Rect;
  SDL_Rect *Enemy17 = new SDL_Rect;
  SDL_Rect *Enemy18 = new SDL_Rect;
  SDL_Rect *Enemy19 = new SDL_Rect;
  SDL_Rect *Enemy20 = new SDL_Rect;
  SDL_Rect *Enemy21 = new SDL_Rect;
  SDL_Rect *Enemy22 = new SDL_Rect;
  SDL_Rect *Enemy23 = new SDL_Rect;
  SDL_Rect *Enemy24 = new SDL_Rect;
  SDL_Rect *Enemy25 = new SDL_Rect;
  SDL_Rect *Enemy26 = new SDL_Rect;
  SDL_Rect *Enemy27 = new SDL_Rect;
  SDL_Rect *Enemy28 = new SDL_Rect;
  SDL_Rect *Enemy29 = new SDL_Rect;
  SDL_Rect *Enemy30 = new SDL_Rect;
  SDL_Rect *Enemy31 = new SDL_Rect;
  SDL_Rect *Enemy32 = new SDL_Rect;
  SDL_Rect *Enemy33 = new SDL_Rect;
  SDL_Rect *Enemy34 = new SDL_Rect;
  SDL_Rect *Enemy35 = new SDL_Rect;
  SDL_Rect *Enemy36 = new SDL_Rect;
  SDL_Rect *Enemy37 = new SDL_Rect;
  SDL_Rect *Enemy38 = new SDL_Rect;
  SDL_Rect *Enemy39 = new SDL_Rect;
  SDL_Rect *Enemy40 = new SDL_Rect;
  SDL_Rect *Enemy41 = new SDL_Rect;
  SDL_Rect *Enemy42 = new SDL_Rect;
  SDL_Rect *Enemy43 = new SDL_Rect;
  SDL_Rect *Enemy44 = new SDL_Rect;
  SDL_Rect *Enemy45 = new SDL_Rect;
  SDL_Rect *Enemy46 = new SDL_Rect;
  SDL_Rect *Enemy47 = new SDL_Rect;
  SDL_Rect *Enemy48 = new SDL_Rect;
  SDL_Rect *Enemy49 = new SDL_Rect;
  SDL_Rect *Enemy50 = new SDL_Rect;
  List.push_back(Enemy1);
  List.push_back(Enemy2);
  List.push_back(Enemy3);
  List.push_back(Enemy4);
  List.push_back(Enemy5);
  List.push_back(Enemy6);
  List.push_back(Enemy7);
  List.push_back(Enemy8);
  List.push_back(Enemy9);
  List.push_back(Enemy10);
  List.push_back(Enemy11);
  List.push_back(Enemy12);
  List.push_back(Enemy13);
  List.push_back(Enemy14);
  List.push_back(Enemy15);
  List.push_back(Enemy16);
  List.push_back(Enemy17);
  List.push_back(Enemy18);
  List.push_back(Enemy19);
  List.push_back(Enemy20);
  List.push_back(Enemy21);
  List.push_back(Enemy22);
  List.push_back(Enemy23);
  List.push_back(Enemy24);
  List.push_back(Enemy25);
  List.push_back(Enemy26);
  List.push_back(Enemy27);
  List.push_back(Enemy28);
  List.push_back(Enemy29);
  List.push_back(Enemy30);
  List.push_back(Enemy31);
  List.push_back(Enemy32);
  List.push_back(Enemy33);
  List.push_back(Enemy34);
  List.push_back(Enemy35);
  List.push_back(Enemy36);
  List.push_back(Enemy37);
  List.push_back(Enemy38);
  List.push_back(Enemy39);
  List.push_back(Enemy40);
  List.push_back(Enemy41);
  List.push_back(Enemy42);
  List.push_back(Enemy43);
  List.push_back(Enemy44);
  List.push_back(Enemy45);
  List.push_back(Enemy46);
  List.push_back(Enemy47);
  List.push_back(Enemy48);
  List.push_back(Enemy49);
  List.push_back(Enemy50);
  return List;
}
